name: (pre)release
on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:
  deploy-ghcr:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker-ghcr.outputs.tags }}
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        id: docker-ghcr
        with:
          image: ${{ github.repository }}
          addLatest: true
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile

  create-ecs-deployment:
    name: Create ECS Deployment
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - name: Create Deployment
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "queued"
          environment: "production"
          description: "Production environment for ${{ github.repository }}"

  deploy-ecr:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: [create-ecs-deployment]
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        id: docker-ecr
        with:
          image: ${{ github.repository }}
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          addLatest: true
          dockerfile: Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update ECS deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "failure"
          deployment_id: ${{ needs.create-ecs-deployment.outputs.deployment_id }}

  deploy-ecs:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: [ deploy-ecr, create-ecs-deployment ]
    steps:
      - name: Update ECS deployment status (pending)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "pending"
          deployment_id: ${{ needs.create-ecs-deployment.outputs.deployment_id }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.AWS_ECS_TASK_DEF }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.AWS_TASK_CONTAINER }}
          image: ${{ secrets.AWS_ECR_REGISTRY }}/${{ github.repository}}:${{ github.ref_name }}

      - name: Update ECS deployment status (in progress)
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "in_progress"
          deployment_id: ${{ needs.create-ecs-deployment.outputs.deployment_id }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.AWS_ECS_SERVICE }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Update ECS deployment status (success)
        uses: chrnorm/deployment-status@releases/v1
        if: success()
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "success"
          deployment_id: ${{ needs.create-ecs-deployment.outputs.deployment_id }}

      - name: Update ECS deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ secrets.HOMEPAGE }}"
          state: "failure"
          deployment_id: ${{ needs.create-ecs-deployment.outputs.deployment_id }}